version: '3.8'

services:
  load-test-app:
    build: .
    container_name: load-test-app
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./logs:/app/logs